# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.account_update_dto import AccountUpdateDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountUpdateDTO(unittest.TestCase):
    """AccountUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountUpdateDTO(self):
        """Test AccountUpdateDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.account_update_dto.AccountUpdateDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
