# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.move_creation_dto import MoveCreationDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestMoveCreationDTO(unittest.TestCase):
    """MoveCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMoveCreationDTO(self):
        """Test MoveCreationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.move_creation_dto.MoveCreationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
