# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.8-rdg
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.faidarev1_contact_dto import Faidarev1ContactDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestFaidarev1ContactDTO(unittest.TestCase):
    """Faidarev1ContactDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFaidarev1ContactDTO(self):
        """Test Faidarev1ContactDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.faidarev1_contact_dto.Faidarev1ContactDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
