# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.faidarev1_last_update_dto import Faidarev1LastUpdateDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestFaidarev1LastUpdateDTO(unittest.TestCase):
    """Faidarev1LastUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFaidarev1LastUpdateDTO(self):
        """Test Faidarev1LastUpdateDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.faidarev1_last_update_dto.Faidarev1LastUpdateDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
