# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unit_details_dto import UnitDetailsDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestUnitDetailsDTO(unittest.TestCase):
    """UnitDetailsDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitDetailsDTO(self):
        """Test UnitDetailsDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unit_details_dto.UnitDetailsDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
