# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.4.7
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pagination_dto import PaginationDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestPaginationDTO(unittest.TestCase):
    """PaginationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginationDTO(self):
        """Test PaginationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pagination_dto.PaginationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
