# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.brapi_data_response_part_list_br_apiv1_call_dto import BrapiDataResponsePartListBrAPIv1CallDTO  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestBrapiDataResponsePartListBrAPIv1CallDTO(unittest.TestCase):
    """BrapiDataResponsePartListBrAPIv1CallDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrapiDataResponsePartListBrAPIv1CallDTO(self):
        """Test BrapiDataResponsePartListBrAPIv1CallDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.brapi_data_response_part_list_br_apiv1_call_dto.BrapiDataResponsePartListBrAPIv1CallDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
