# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.api_contact_info_dto import ApiContactInfoDTO  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestApiContactInfoDTO(unittest.TestCase):
    """ApiContactInfoDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiContactInfoDTO(self):
        """Test ApiContactInfoDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.api_contact_info_dto.ApiContactInfoDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
