# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.faidarev1_scale_dto import Faidarev1ScaleDTO  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestFaidarev1ScaleDTO(unittest.TestCase):
    """Faidarev1ScaleDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFaidarev1ScaleDTO(self):
        """Test Faidarev1ScaleDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.faidarev1_scale_dto.Faidarev1ScaleDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
