# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.agroportal_ontologies_config_dto import AgroportalOntologiesConfigDTO  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestAgroportalOntologiesConfigDTO(unittest.TestCase):
    """AgroportalOntologiesConfigDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgroportalOntologiesConfigDTO(self):
        """Test AgroportalOntologiesConfigDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.agroportal_ontologies_config_dto.AgroportalOntologiesConfigDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
