# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.favorite_get_dto import FavoriteGetDTO  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestFavoriteGetDTO(unittest.TestCase):
    """FavoriteGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFavoriteGetDTO(self):
        """Test FavoriteGetDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.favorite_get_dto.FavoriteGetDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
