# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.status_dto import StatusDTO  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestStatusDTO(unittest.TestCase):
    """StatusDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusDTO(self):
        """Test StatusDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.status_dto.StatusDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
