# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.br_apiv1_germplasm_list_response import BrAPIv1GermplasmListResponse  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestBrAPIv1GermplasmListResponse(unittest.TestCase):
    """BrAPIv1GermplasmListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrAPIv1GermplasmListResponse(self):
        """Test BrAPIv1GermplasmListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.br_apiv1_germplasm_list_response.BrAPIv1GermplasmListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
