# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: BUILD-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import opensilex_swagger_client
from opensilex_swagger_client.models.events_import_validation_body import EventsImportValidationBody  # noqa: E501
from opensilex_swagger_client.rest import ApiException


class TestEventsImportValidationBody(unittest.TestCase):
    """EventsImportValidationBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventsImportValidationBody(self):
        """Test EventsImportValidationBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = opensilex_swagger_client.models.events_import_validation_body.EventsImportValidationBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
